### ISSUE TITLE
Better support for angular filters

### ISSUE THREAD

**Issue by Athaphian** [fvanwijk/mox#25]
I couldn't really get mox to mock my angular custom filter. It would be nice if it was supported as a top level method next to mockServices, mockDirectives, mockControllers etc: mockFilters.

This is the code that I currently use to make it work:

```
    module(function ($provide) {
      $provide.value('myFltrFilter', function (input) {
        return input;
      });
    });

    mox
      .module('myModule')
      .mockServices('$state', 'SomeService')
      .setupResults(function () {
        return {
          SomeService: {}
        };
      })
      .run();
```

I did try to mock my filter with mox in various ways, since it is suggested in the documentation, but I could not get it to work.. if it is supported, can I get a clear example of how to do it?

I tried for instance:
```
mox.mockServices('myFltr')
mox.mockServices('myFltrFilter')

mox.setupResults(function () {
        return {
          MyFltr: '',
          MyFltrFilter: ''
        };
      })

```

**Comment by fvanwijk** [comment]
Hi @Athaphian, thanks for creating this issue.

Mocking filters shouldn't be any problem via `.mockServices(function() { ... })`. I will soon (I'm on holiday right now) update the `fvanwijk/mox-example` repo because you are right that this should be more clear from the documentation.

**Comment by fvanwijk** [comment]
I'm not sure if your example code is exactly what you tried, because the `MyFltr` key of `setupResults` will throw an error because Angular cannot inject it.

I think it also happens to `MyFltrFilter` because the first letter should be a lowercase 'm'. This typo might be the reason why the Mox way didn't work in your code, while the `$provide.value('myFltrFilter', ...)` way works.

As promised I updated the examples, so you can see how to test and how to mock a filter with and without Mox:
https://github.com/fvanwijk/mox-example/pull/1/files
